config/routes.rb
Rails.application.routes.draw do
  
  resources :homework_twos
  get 'greetings/hello'

  get 'greetings/bye'

end

app/models/homework_two.rb
class HomeworkTwo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/greetings_controller.rb
class GreetingsController < ApplicationController
  def hello
        timeget=Time.new
	yearNow =timeget.year.to_s
	monthNow =timeget.month.to_s
	dayNow =timeget.day.to_s
	hourNow =timeget.hour.to_s
	minuteNow =timeget.min.to_s
	secondNow =timeget.sec.to_s
	@timenow=yearNow+'年'+monthNow+'月'+dayNow+'日'+' '+hourNow+':'+minuteNow+':'+secondNow
	@message = "Hello, How Are You Today?"
  end

  def bye
  end
end    

app/controllers/homework_twos_controller.rb
class HomeworkTwosController < ApplicationController
  before_action :set_homework_two, only: [:show, :edit, :update, :destroy]

  # GET /homework_twos
  # GET /homework_twos.json
  def index
    @homework_twos = HomeworkTwo.all
  end

  # GET /homework_twos/1
  # GET /homework_twos/1.json
  def show
  end

  # GET /homework_twos/new
  def new
    @homework_two = HomeworkTwo.new
  end

  # GET /homework_twos/1/edit
  def edit
  end

  # POST /homework_twos
  # POST /homework_twos.json
  def create
    @homework_two = HomeworkTwo.new(homework_two_params)

    respond_to do |format|
      if @homework_two.save
        format.html { redirect_to @homework_two, notice: 'Homework two was successfully created.' }
        format.json { render :show, status: :created, location: @homework_two }
      else
        format.html { render :new }
        format.json { render json: @homework_two.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homework_twos/1
  # PATCH/PUT /homework_twos/1.json
  def update
    respond_to do |format|
      if @homework_two.update(homework_two_params)
        format.html { redirect_to @homework_two, notice: 'Homework two was successfully updated.' }
        format.json { render :show, status: :ok, location: @homework_two }
      else
        format.html { render :edit }
        format.json { render json: @homework_two.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homework_twos/1
  # DELETE /homework_twos/1.json
  def destroy
    @homework_two.destroy
    respond_to do |format|
      format.html { redirect_to homework_twos_url, notice: 'Homework two was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_homework_two
      @homework_two = HomeworkTwo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def homework_two_params
      params.require(:homework_two).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/greetings_helper.rb
module GreetingsHelper
end

app/helpers/homework_twos_helper.rb
module HomeworkTwosHelper
end

app/views/greetings/bye.html.erb
<head>
    
</head>
  <p></p>
   <p><%=  link_to 'Click here to go back!',greetings_hello_path  %></p>

app/views/greetings/hello.html.erb
<h1> Homework of Software Engineering</h1>
<p><%=  @message  %></p>
<br><a href="http://www.ucas.edu.cn/">UCAS</a><br>

<p>Time: <%=  @timenow  %></p>
<p><%=  link_to 'BYE',greetings_bye_path  %></p>

app/views/homework_twos/_form.html.erb
<%= form_for(@homework_two) do |f| %>
  <% if @homework_two.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@homework_two.errors.count, "error") %> prohibited this homework_two from being saved:</h2>

      <ul>
      <% @homework_two.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homework_twos/edit.html.erb
<h1>Editing Homework Two</h1>

<%= render 'form' %>

<%= link_to 'Show', @homework_two %> |
<%= link_to 'Back', homework_twos_path %>

app/views/homework_twos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students' information</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homework_twos.each do |homework_two| %>
      <tr>
        <td><%= homework_two.name %></td>
        <td><%= homework_two.email %></td>
        <td><%= link_to 'Show', homework_two %></td>
        <td><%= link_to 'Edit', edit_homework_two_path(homework_two) %></td>
        <td><%= link_to 'Destroy', homework_two, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Click here to add information', new_homework_two_path %>

app/views/homework_twos/new.html.erb
<h1>New Homework Two</h1>

<%= render 'form' %>

<%= link_to 'Back', homework_twos_path %>

app/views/homework_twos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @homework_two.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @homework_two.email %>
</p>

<%= link_to 'Edit', edit_homework_two_path(@homework_two) %> |
<%= link_to 'Back', homework_twos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Markapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>